apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: chert

resources:
  - namespace.yaml
  - service.yaml
  - deployment.yaml

images:
  - name: chert-standalone-image
    newName: harbor.281018.xyz/chert/chert-standalone
    newTag: latest
